### ISSUE TITLE
Python 3.11.9 fresh install fails

### ISSUE THREAD

**Issue by dixon1e** [SynaLinks/HybridAGI#11]
**Describe the bug**
Poetry install fails with the following error:

Package operations: 1 install, 0 updates, 0 removals
  - Installing tree-sitter-python (0.21.0): Failed
  RuntimeError
  Unable to find installation candidates for tree-sitter-python (0.21.0)

**To Reproduce**
Followed installation instructions:
1. git clone repo
2. python virtualenv created
3. pip install poetry
4. poetry install

**Expected behavior**
poetry install should complete successfully

**Desktop (please complete the following information):**
MacOS Sonoma 12.7.1
Macbook Pro M3

**Additional context**
Python 3.11.9 was installed using Homebrew. The "system" python is 3.9.x

**Comment by YoanSallami** [comment]
Hello, thank you for you feedback ! :) I'm looking into it, python tree-sitter was upgraded recently.. can you do `pip show tree-sitter-python` to check the version available for your system?

**Comment by YoanSallami** [comment]
https://pypi.org/project/tree-sitter-python/ the 0.21.0 is still available in pypi, they recently upgraded the repository to 0.22.3. I'm checking to make it optional then..

**Comment by dixon1e** [comment]
The version installed is indeed 0.22.3.

dcd

**Comment by YoanSallami** [comment]
I found the problem https://github.com/tree-sitter/tree-sitter-python/issues/262  I'm updating the pyproject.toml, tell me if it solves your install problems :)

**Comment by dixon1e** [comment]
Fresh install now works. Well handled, thank you!

dcd

**Comment by dixon1e** [comment]
Installs correctly on Python 3.11.9.
