### ISSUE TITLE
code interpreter bug 

### ISSUE THREAD

**Issue by saakethch** [SynaLinks/HybridAGI#15]
**Describe the bug**
can not get plot results on calling code interpreter with a plotting code 

**To Reproduce**
`

    def test_code_interpreter_plots():

        
        interpreter = CodeInterpreterUtility()
        interpreter.reset()

        code = \
        """
        import matplotlib.pyplot as plt

        # Générer des données aléatoires
        x = np.arange(10)  # Générer une séquence de 10 nombres (0 à 9)
        y = np.random.rand(10)  # Générer 10 nombres aléatoires

        print(x)
        print(y)
        print("hello")
        plt.plot(x, y)
        # Ajouter des titres et des étiquettes
        # plt.title('Graphique Simple avec Matplotlib')
        # plt.xlabel('Index')
        # plt.ylabel('Valeur aléatoire')

        # # Afficher le graphique
        # plt.show()
        """
        result, plots, err = interpreter.add_and_run(code)
        print("-------------------------------------------------------------", result, plots, err)
    
    
    test_code_interpreter_plots() results in 
    `
    --------------------------------- [0 1 2 3 4 5 6 7 8 9]
[0.85200231 0.94347675 0.0986986  0.82908233 0.12819016 0.92702133
 0.23153489 0.78100707 0.57922956 0.33323378]
hello

---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Cell In[3], line 10
      8 print(y)
      9 print("hello")
---> 10 plt.plot(x, y)
     11 # Ajouter des titres et des étiquettes
     12 # plt.title('Graphique Simple avec Matplotlib')
     13 # plt.xlabel('Index')
   (...)
     16 # # Afficher le graphique
     17 # plt.show()

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\matplotlib\pyplot.py:3708, in plot(scalex, scaley, data, *args, **kwargs)
   3700 @_copy_docstring_and_deprecators(Axes.plot)
   3701 def plot(
   3702     *args: float | ArrayLike | str,
   (...)
   3706     **kwargs,
   3707 ) -> list[Line2D]:
-> 3708     return gca().plot(
   3709         *args,
   3710         scalex=scalex,
   3711         scaley=scaley,
   3712         **({"data": data} if data is not None else {}),
   3713         **kwargs,
   3714     )`
 Afficher le graphique
plt.show()

----------` 

- OS: Windows, Python

**Comment by YoanSallami** [comment]
Hello, thank you for your support and feedback ! This function returns the plot as a PIL image, which cannot be printed with print (it is not a text but an image). For now as DSPy don't manage vision this feature is not possible as is... I'm however working on it to find a better way to integrate it.
