### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by acazau** [SynaLinks/HybridAGI#18]
https://github.com/SynaLinks/HybridAGI/blob/e46de85421320b89ea355cacbff3a558b79be8d1/hybridagi/retrievers/entity.py#L55

While adding a unit test for  EnitityRetrieve as part of a separate body of work, I noticed  record has 3 elements with the distance being record[2] instead of current record[1]

Example output:
 ['London', 'London', 0.669780731201172]

**Comment by YoanSallami** [comment]
I close this issue because related to https://github.com/SynaLinks/HybridAGI/issues/17
