### ISSUE TITLE
Can you please share the road map or vision of the Project

### ISSUE THREAD

**Issue by mahimairaja** [SynaLinks/HybridAGI#7]
Hey, I find the idea behind the project very interesting and would love to contribute. It would be more meaningful if you could add the roadmap of the project to the repo through a project board or the issues list. Looking forward to connect for a meaningful engagement! 

Cheers

**Comment by YoanSallami** [comment]
Hello, thank you for your support ! I'm looking into that and I'll keep you updated very soon ! I can definitely at least make a features list for the short term as I already know how to implement the other memory types inspired by human cognition (for now we have the declarative and episodic memory, but we lack the biographic one)

**Comment by YoanSallami** [comment]
I've made some enhancement issues that you can check, I advise you to join the discord and discuss them so we can all together progress towards safe AI systems :)
